Update kernel_build.yml
Signed-off-by: Paul Luse <paul.e.luse@intel.com>

diff --git a/.github/workflows/kernel_build.yml b/.github/workflows/kernel_build.yml
--- a/.github/workflows/kernel_build.yml
+++ b/.github/workflows/kernel_build.yml
@@ -134,7 +134,11 @@ jobs:
       - name: Execute tests
         run: |
           cp .github/run_fio.py .
-          python3 ./run_fio.py
+          vagrant status
+          sleep 2
+          vagrant ssh -c "sudo python3 ./run_fio.py"
+          echo "FYI vagrant run_fio.py done command finished with exit code: $?" || \
+          (echo "Error: vagrant run_fio.py command failed!" && exit 1)         
       - name: All done, cleanup
         run: |          
           cd ..
